// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdwrkwnzigdsniumiatk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkd3Jrd256aWdkc25pdW1pYXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTc4NDMsImV4cCI6MjA2NTQ5Mzg0M30.ppsQmLDzxrg5OqNlPSOu9B8iqanNeAgd1n9Odgepq30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);